'use client';
import {Suspense,useEffect,useState} from 'react';
import {useParams,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import api,{errorMessage} from '@/utils/api';
import {ResearchCase,buttonClass,numberFormat as fmt} from '@/utils/research';

function Report(){
 const {id}=useParams<{id:string}>();const search=useSearchParams();const revision=search.get('revision');
 const [record,setRecord]=useState<ResearchCase|null>(null),[error,setError]=useState('');
 useEffect(()=>{let active=true;api.get(`/research/cases/${id}${revision?`/revisions/${encodeURIComponent(revision)}`:''}`).then(({data})=>{if(active)setRecord(data);}).catch(e=>{if(active)setError(errorMessage(e));});return ()=>{active=false;};},[id,revision]);
 if(error)return <p role="alert">{error}</p>;
 if(!record)return <p role="status">Loading saved report…</p>;
 const {draft,evaluation}=record;
 return <div className="mx-auto max-w-4xl"><nav aria-label="Report actions" className="no-print mb-7 flex flex-wrap gap-3"><Link className={buttonClass} href={`/research/${id}`}>Back to case</Link><button className={buttonClass} onClick={()=>window.print()}>Print / save PDF</button><a className={buttonClass} href={`/api/research/cases/${id}/report?revision=${record.revision}`}>Download Markdown</a><a className={buttonClass} href={`/api/research/cases/${id}/export?revision=${record.revision}`}>Download research JSON</a></nav>
 <article className="research-report space-y-8 border border-slate-200 bg-white p-5 sm:p-10"><header className="border-b-2 border-brand-700 pb-6"><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand-800">Vertige · Company research</p><h1 className="mt-4 text-3xl font-semibold">{draft.company_name}</h1><p className="mt-2 text-sm text-slate-600">{draft.ticker} · {draft.currency} · Reference date {draft.as_of} · Revision {record.revision}</p><p className="mt-3 text-xs text-slate-500">Saved {new Date(record.saved_at).toLocaleString()} · {draft.data_origin} inputs · {draft.status} workflow status</p></header>
 <section><h2 className="text-lg font-semibold">Investment thesis</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{draft.thesis||'Not recorded.'}</p></section>
 <section><h2 className="text-lg font-semibold">Valuation</h2><p className="mt-3 text-2xl font-semibold tabular-nums">{draft.currency} {fmt(evaluation.weighted_price)} <span className="text-sm font-normal text-slate-600">scenario-weighted value</span></p><p className="mt-2 text-sm">Reference price {fmt(draft.financials.current_price)}; {fmt(evaluation.weighted_upside)}% implied upside/downside.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[410px] text-right text-sm tabular-nums"><thead><tr>{['Scenario','Weight','WACC','Growth','Value'].map(x=><th key={x} className="p-2 text-xs font-medium">{x}</th>)}</tr></thead><tbody>{draft.scenarios.map(s=><tr className="border-t border-slate-200" key={s.key}><th className="p-2 text-left font-medium capitalize">{s.key}</th>{[s.probability*100,s.wacc*100,s.terminal_growth*100].map((x,i)=><td key={i} className="p-2">{fmt(x)}%</td>)}<td className="p-2">{fmt(evaluation.scenarios[s.key].result.implied_price)}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-6 text-slate-600">{evaluation.description} Year-end FCFF, Gordon terminal value and changes in operating working capital. Money and shares use millions. No immediate tax benefit on losses.</p></section>
 <section><h2 className="text-lg font-semibold">Financial baseline</h2><dl className="mt-3 grid gap-x-6 sm:grid-cols-2">{Object.entries(draft.financials).map(([k,v])=><div key={k} className="flex justify-between gap-3 border-b border-slate-100 py-2 text-xs"><dt className="capitalize">{k.replaceAll('_',' ')}</dt><dd>{fmt(v)}</dd></div>)}</dl><p className="mt-2 text-xs text-slate-500">Baseline ratios are decimals: 0.25 means 25%.</p></section>
 <section className="space-y-5"><h2 className="text-lg font-semibold">Scenario reasoning</h2>{draft.scenarios.map(s=><div key={s.key}><h3 className="font-semibold capitalize">{s.key}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{s.rationale||'Rationale not recorded.'}</p><p className="mt-2 text-xs">Annual revenue growth: {s.growth_rates.map(x=>`${fmt(x*100)}%`).join(', ')}.<br/>Annual EBIT margin: {s.ebit_margins.map(x=>`${fmt(x*100)}%`).join(', ')}.</p>{evaluation.scenarios[s.key].result.warnings.map(w=><p key={w} className="mt-2 text-xs text-amber-900">{w}</p>)}</div>)}</section>
 <section><h2 className="text-lg font-semibold">Catalysts</h2>{draft.catalysts.length?<ul className="mt-3 space-y-2 text-sm">{draft.catalysts.map((c,i)=><li key={i}>{c.title} · {c.due_date||'Undated'} · {c.status}</li>)}</ul>:<p className="mt-3 text-sm">Not recorded.</p>}</section>
 {([['risks','Risks'],['invalidation','What would change the thesis'],['decision_notes','Decision notes']] as const).map(([key,title])=><section key={key}><h2 className="text-lg font-semibold">{title}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{draft[key]||'Not recorded.'}</p></section>)}
 <section><h2 className="text-lg font-semibold">Source register</h2>{draft.sources.length?<ol className="mt-3 list-decimal space-y-4 pl-5">{draft.sources.map((source,i)=><li key={i} className="text-sm"><a href={source.url} target="_blank" rel="noreferrer" className="break-words font-medium text-brand-800 underline">{source.title}</a><p className="mt-1 text-xs text-slate-500">{source.published_date||'Publication date not recorded'}</p><p className="mt-1 whitespace-pre-wrap text-sm">{source.supports||'Supporting assumption not recorded.'}</p><p className="mt-1 break-all text-xs text-slate-500">{source.url}</p></li>)}</ol>:<p className="mt-3 text-sm">No sources recorded.</p>}<p className="mt-3 text-xs text-slate-600">References were entered by the analyst. Their contents have not been fetched or verified by this report.</p></section>
 <section><h2 className="text-lg font-semibold">Open items and next review</h2><p className="mt-3 text-sm">Next review: {draft.review_date||'Not scheduled'}.</p><ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{evaluation.research_gaps.map(g=><li key={g}>{g}</li>)}</ul></section>
 <footer className="border-t border-slate-300 pt-5 text-xs leading-6 text-slate-500"><p>Calculation version {evaluation.calculation_version}. Research status is an analyst label, not certification. This report is a saved scenario analysis, not a live market feed or investment recommendation.</p><p className="mt-2 break-all">Input fingerprint: {record.input_sha256}</p></footer></article></div>;
}
export default function ResearchReport(){return <Suspense fallback={<p>Loading report…</p>}><Report/></Suspense>;}
