'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import api,{errorMessage} from '@/utils/api';
import {CaseSummary,initialDraft,ResearchDraft,fieldClass,buttonClass,primaryClass,numberFormat as fmt} from '@/utils/research';

export default function ResearchLibrary(){
 const creationRequest=useRef<{id:string;inputs:string}|null>(null);
 const router=useRouter();const [cases,setCases]=useState<CaseSummary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('active'),[mode,setMode]=useState<'closed'|'create'|'import'>('closed'),[draft,setDraft]=useState(initialDraft),[importText,setImportText]=useState('');
 const [providerNotice,setProviderNotice]=useState('');
 async function refresh(){setLoading(true);setError('');try{setCases((await api.get('/research/cases')).data);}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),ticker=params.get('ticker');if(ticker){setDraft(value=>({...value,ticker:ticker.slice(0,25).toUpperCase(),company_name:(params.get('name')||ticker).slice(0,160)}));setMode('create');}},[]);
 async function providerBaseline(){setBusy(true);setError('');setProviderNotice('');try{const {data}=await api.get(`/market/${encodeURIComponent(draft.ticker)}`);const p=data.provenance;const quoteDate=p.price_as_of?new Date(p.price_as_of*1000).toISOString().slice(0,10):new Date().toISOString().slice(0,10);setDraft(value=>({...value,ticker:data.ticker,company_name:data.company_name,currency:data.currency,as_of:quoteDate,financials:{...value.financials,current_price:data.current_price,shares_outstanding_m:data.shares_outstanding_m,net_debt_m:data.net_debt_m,start_revenue_m:data.start_revenue_m},sources:[...value.sources,{title:`${data.ticker} provider baseline`,url:`https://finance.yahoo.com/quote/${encodeURIComponent(data.ticker)}/`,published_date:null,supports:`Yahoo Finance via yfinance, fetched ${p.fetched_at}. Quote date ${quoteDate}; financial period ${p.financial_period_end?new Date(p.financial_period_end*1000).toISOString().slice(0,10):'unavailable'}. Revenue, price, shares and net debt supplied. Shares are not a verified diluted count.`}]}));setProviderNotice('Provider baseline loaded with a source record. Verify periods and dilution. Forecast scenarios and other assumptions remain illustrative until you review them.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function create(value:ResearchDraft){setBusy(true);setError('');const inputs=JSON.stringify(value);if(creationRequest.current?.inputs!==inputs)creationRequest.current={id:crypto.randomUUID(),inputs};try{const {data}=await api.post('/research/cases',{request_id:creationRequest.current.id,draft:value});router.push(`/research/${data.id}`);}catch(e){setError(errorMessage(e));setBusy(false);}}
 const shown=cases.filter(c=>(filter==='all'||(filter==='active'?c.status!=='archived':c.status===filter))&&`${c.company_name} ${c.ticker}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="mx-auto max-w-7xl space-y-8"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-300 pb-7"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-brand-700">Research desk</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Your company research</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Keep the thesis, evidence and valuation together. Every saved revision retains its assumptions and calculated results.</p></div><div className="flex flex-wrap gap-3"><button className={buttonClass} onClick={()=>setMode(mode==='import'?'closed':'import')}>Import research JSON</button><button className={primaryClass} onClick={()=>setMode(mode==='create'?'closed':'create')}>New research case</button></div></header>
 {error&&<p role="alert" className="border-l-4 border-red-700 bg-red-50 p-4 text-sm text-red-900">{error}</p>}
 {mode==='create'&&<form className="space-y-5 border-b border-slate-300 pb-7" onSubmit={e=>{e.preventDefault();create(draft);}}><h2 className="text-lg font-semibold">Start a company case</h2><p className="text-sm text-slate-600">Enter a consistent financial baseline. The scenario assumptions begin as illustrative inputs for you to revise.</p><fieldset disabled={busy} className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(['company_name','ticker','currency'] as const).map(k=><label className="text-xs font-medium" key={k}>{k==='company_name'?'Company name':k==='ticker'?'Ticker':'Currency'}<input required className={fieldClass} value={draft[k]} onChange={e=>setDraft({...draft,[k]:k==='company_name'?e.target.value:e.target.value.toUpperCase()})}/></label>)}<label className="text-xs font-medium">Reference date<input type="date" required className={fieldClass} value={draft.as_of} onChange={e=>setDraft({...draft,as_of:e.target.value})}/></label>{([['current_price','Share price'],['start_revenue_m','Revenue (millions)'],['shares_outstanding_m','Diluted shares (millions)'],['net_debt_m','Net debt (millions)']] as const).map(([k,label])=><label key={k} className="text-xs font-medium">{label}<input type="number" step="any" required className={fieldClass} value={draft.financials[k]} onChange={e=>setDraft({...draft,financials:{...draft.financials,[k]:Number(e.target.value)}})}/></label>)}</fieldset><div className="flex flex-wrap gap-3"><button type="button" disabled={busy} className={buttonClass} onClick={providerBaseline}>Load provider baseline</button><button disabled={busy} className={primaryClass}>{busy?'Working…':'Create case'}</button></div>{providerNotice&&<p role="status" className="text-sm text-slate-600">{providerNotice}</p>}</form>}
 {mode==='import'&&<form className="space-y-4 border-b border-slate-300 pb-7" onSubmit={e=>{e.preventDefault();try{const parsed=JSON.parse(importText);if(parsed.format!=='vertige-research'||parsed.version!==1||!parsed.draft)throw new Error('Paste an exported Vertige research JSON file.');create(parsed.draft);}catch(e){setError(errorMessage(e));}}}><label className="block text-sm font-medium">Exported research JSON<textarea required value={importText} onChange={e=>setImportText(e.target.value)} className={fieldClass+' h-40 font-mono text-xs'} maxLength={300000}/></label><p className="text-xs text-slate-600">Creates a separate case. Saved calculations from the file are ignored; all scenarios are recalculated from validated inputs.</p><button disabled={busy} className={primaryClass}>{busy?'Importing…':'Import as new case'}</button></form>}
 <div className="flex flex-wrap items-end gap-4"><label className="min-w-48 flex-1 text-xs font-medium">Find a company<input type="search" className={fieldClass} placeholder="Company or ticker" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="text-xs font-medium">Workflow<select className={fieldClass} value={filter} onChange={e=>setFilter(e.target.value)}>{['active','all','watching','researching','reviewed','archived'].map(x=><option key={x} value={x}>{x[0].toUpperCase()+x.slice(1)}</option>)}</select></label><button className={buttonClass} disabled={loading} onClick={refresh}>Refresh</button></div>
 {loading?<p role="status" className="py-12 text-sm text-slate-600">Loading saved research…</p>:!cases.length?<section className="border-y border-slate-200 py-14"><h2 className="text-xl font-semibold">A research file starts with a question.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">Create your first company case, or explore an explicitly illustrative example. Add your sources, test three scenarios and record what would change your view.</p><button disabled={busy} onClick={()=>create(initialDraft())} className={buttonClass+' mt-5'}>Try an illustrative case</button></section>:!shown.length?<p role="status" className="py-10 text-sm">No cases match these filters.</p>:<div className="overflow-x-auto border-y border-slate-300"><table className="w-full min-w-[700px] text-sm"><caption className="sr-only">Saved research cases with subjective scenario-weighted values</caption><thead className="bg-slate-100 text-left text-xs text-slate-600"><tr>{['Company','Reference price','Weighted value','Research record','Review','Status'].map(x=><th className="px-3 py-3 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{shown.map(c=><tr key={c.id} className="border-t border-slate-200"><td className="px-3 py-4"><Link className="font-semibold text-brand-800 underline-offset-4 hover:underline" href={`/research/${c.id}`}>{c.company_name}</Link><p className="mt-1 text-xs text-slate-500">{c.ticker} · {c.currency} · {c.data_origin}</p></td><td className="px-3 py-4 tabular-nums">{fmt(c.current_price)}<p className="mt-1 text-xs text-slate-500">{c.as_of}</p></td><td className="px-3 py-4 tabular-nums">{fmt(c.weighted_price)}<p className="mt-1 text-xs text-slate-500">{fmt(c.weighted_upside)}% vs reference</p></td><td className="px-3 py-4">{c.source_count} sources<p className="mt-1 text-xs text-slate-500">Revision {c.revision} · {c.gap_count} open items</p></td><td className="px-3 py-4">{c.review_date||'Not scheduled'}</td><td className="px-3 py-4 capitalize">{c.status}</td></tr>)}</tbody></table></div>}
 <p className="text-xs leading-6 text-slate-500">Saved on this server in a local SQLite database. Exports provide a portable copy. Workflow labels and source links are analyst records, not independent verification. Values in different currencies are not directly comparable.</p></div>;
}
