'use client';
import {useState} from 'react';
import api,{errorMessage} from '@/utils/api';
const defaults={noi:1200,cap_rate:.045,other_assets:500,total_debt:8000,minority_interest:0,preferred_equity:0,shares_outstanding:150};
const resourceDefaults={reserves:500,value_per_unit:80,production_cost_per_unit:30,exploration_upside:500,liabilities:2000,shares_outstanding:100};
export default function AdvancedNAV(){
 const [mode,setMode]=useState('real-estate'),[real,setReal]=useState(defaults),[resource,setResource]=useState(resourceDefaults);
 const [result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const values=mode==='real-estate'?real:resource;
 const labels:Record<string,string>={noi:'Annual NOI (M)',cap_rate:'Capitalization rate (decimal)',other_assets:'Other assets (M)',total_debt:'Debt (M)',minority_interest:'Minority interest (M)',preferred_equity:'Preferred equity (M)',shares_outstanding:'Diluted shares (M)',reserves:'Reserves (M units)',value_per_unit:'Value per reserve unit',production_cost_per_unit:'Production cost per unit',exploration_upside:'Exploration value (M)',liabilities:'Liabilities (M)'};
 return <section className="space-y-5"><div className="rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-2xl font-semibold">Net asset value</h2><p className="mt-2 text-sm text-slate-300">Review every asset value and claim. Initial inputs are illustrative; use one currency throughout.</p></div><div className="flex gap-2">{['real-estate','resource'].map(m=><button disabled={busy} key={m} onClick={()=>{setMode(m);setResult(null);setError('');}} className={`rounded-lg px-4 py-2 text-sm ${mode===m?'bg-brand-600 text-white':'border bg-white'}`}>{m==='real-estate'?'Real estate':'Resources'}</button>)}</div>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}
 <form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setResult(null);try{setResult((await api.post(`/valuation/nav/${mode}`,values)).data);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}}><fieldset disabled={busy} className="rounded-2xl border bg-white p-6"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{Object.entries(values).map(([k,v])=><label key={k} className="text-xs text-slate-600">{labels[k]}<input aria-label={labels[k]} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" type="number" step="any" required value={v} onChange={e=>{const updated={...values,[k]:Number(e.target.value)};if(mode==='real-estate')setReal(updated as typeof real);else setResource(updated as typeof resource);setResult(null);}}/></label>)}</div><p className="mt-5 text-xs text-slate-500">{mode==='real-estate'?'Property value = annual NOI ÷ cap rate. Equity NAV deducts debt, minority interest and preferred equity.':'Resource value = reserves × (unit value − unit production cost). This simplified asset estimate excludes production timing and discounting; it is not a reserve cash-flow model.'}</p><button className="mt-5 rounded-lg bg-brand-600 px-5 py-3 font-semibold text-white" type="submit">{busy?'Calculating…':'Calculate NAV'}</button></fieldset></form>
 {result&&<div data-testid="nav-results" className="grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-3">{[['Asset value (M)',result.gross_asset_value??result.reserve_value],['Equity NAV (M)',result.net_asset_value],['NAV per share',result.nav_per_share]].map(([label,value])=><div key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{Number(value).toLocaleString(undefined,{maximumFractionDigits:2})}</p></div>)}</div>}
 </section>;
}
