'use client';
import {useState} from 'react';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ReferenceLine,ResponsiveContainer} from 'recharts';
import {ResearchCase,ScenarioKey,fieldClass,numberFormat as fmt} from '@/utils/research';

export default function ResearchResults({record}:{record:ResearchCase}){
 const [focus,setFocus]=useState<ScenarioKey>('base');const {draft,evaluation}=record;
 const rows=draft.scenarios.map(s=>({name:s.key[0].toUpperCase()+s.key.slice(1),value:evaluation.scenarios[s.key].result.implied_price}));
 const result=evaluation.scenarios[focus].result;
 return <section data-testid="research-results" className="space-y-7"><div className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-200 pb-5"><div><p className="text-xs font-medium uppercase tracking-wider text-slate-600">Scenario-weighted value</p><p className="mt-2 text-3xl font-semibold tabular-nums">{draft.currency} {fmt(evaluation.weighted_price)}</p><p className="mt-2 text-sm text-slate-600">{fmt(evaluation.weighted_upside)}% versus the reference price of {fmt(draft.financials.current_price)}</p></div><p className="max-w-sm text-xs leading-6 text-slate-500">Saved revision {record.revision} · {draft.as_of}<br/>{evaluation.description}</p></div>
 <div className="grid gap-7 lg:grid-cols-2"><div aria-label="Scenario value comparison" className="min-w-0"><ResponsiveContainer width="100%" height={220}><BarChart layout="vertical" data={rows} margin={{top:10,right:30,bottom:10,left:0}}><XAxis type="number" tickFormatter={x=>fmt(Number(x))} tick={{fontSize:11}}/><YAxis type="category" dataKey="name" width={48} tick={{fontSize:12}}/><Tooltip formatter={(x:number)=>[`${draft.currency} ${fmt(x)}`,'Value per share']}/><ReferenceLine x={draft.financials.current_price} stroke="#b17a36" strokeDasharray="4 4"/><Bar dataKey="value" fill="#4f46e5" maxBarSize={26}/></BarChart></ResponsiveContainer><p className="text-xs text-slate-500">Dashed line: reference market price. Exact values appear in the adjacent table.</p></div><div className="overflow-x-auto"><table className="w-full text-right text-sm tabular-nums"><caption className="sr-only">Scenario assumptions and values in {draft.currency} per share</caption><thead><tr>{['Case','Weight','Value','Upside'].map(x=><th key={x} className="p-3 text-xs font-medium text-slate-600">{x}</th>)}</tr></thead><tbody>{draft.scenarios.map(s=><tr key={s.key} className="border-t border-slate-200"><th className="p-3 text-left font-medium capitalize">{s.key}</th><td className="p-3">{fmt(s.probability*100)}%</td><td className="p-3">{fmt(evaluation.scenarios[s.key].result.implied_price)}</td><td className="p-3">{fmt(evaluation.scenarios[s.key].result.upside)}%</td></tr>)}</tbody></table></div></div>
 <div className="border-t border-slate-200 pt-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-lg font-semibold">Trace the calculation</h2><label className="text-xs font-medium">Inspect forecast<select className={fieldClass} value={focus} onChange={e=>setFocus(e.target.value as ScenarioKey)}>{['bear','base','bull'].map(k=><option key={k} value={k}>{k[0].toUpperCase()+k.slice(1)}</option>)}</select></label></div>{result.warnings.map(w=><p key={w} className="mt-3 bg-amber-50 p-3 text-sm text-amber-950">{w}</p>)}<div className="mt-5 overflow-auto"><table className="w-full min-w-[420px] text-right text-sm tabular-nums"><caption className="mb-3 text-left text-xs text-slate-500">{draft.currency} millions. Year-end discounting; operating working capital uses a balance ratio.</caption><thead><tr>{['Year','Revenue','EBIT','FCFF','Present value'].map(x=><th key={x} className="p-2 text-xs font-medium">{x}</th>)}</tr></thead><tbody>{result.forecast.map(row=><tr key={row.year} className="border-t border-slate-200">{[row.year,row.revenue,row.ebit,row.fcff,row.pv_fcff].map((x,i)=><td key={i} className="p-2">{fmt(x)}</td>)}</tr>)}</tbody></table></div><dl className="mt-6 grid gap-x-7 sm:grid-cols-2">{Object.entries(result.bridge).map(([k,v])=><div key={k} className="flex justify-between gap-3 border-b border-slate-200 py-2 text-sm"><dt className="capitalize">{k.replaceAll('_',' ')}</dt><dd className="tabular-nums">{fmt(v)}</dd></div>)}</dl></div>
 <details className="border-t border-slate-200 pt-5"><summary className="cursor-pointer font-semibold">Base-case sensitivity</summary><p className="my-3 text-xs text-slate-600">Value per share. Columns vary WACC; rows vary perpetual growth. A dash means the rate pair is invalid.</p><div className="overflow-x-auto"><table className="w-full min-w-[420px] text-right text-sm tabular-nums"><thead><tr><th className="p-2 text-xs">Growth / WACC</th>{evaluation.sensitivity.wacc_values.map(w=><th className="p-2 text-xs" key={w}>{fmt(w*100)}%</th>)}</tr></thead><tbody>{evaluation.sensitivity.growth_values.map((g,i)=><tr key={g} className="border-t border-slate-200"><th className="p-2 text-xs">{fmt(g*100)}%</th>{evaluation.sensitivity.prices[i].map((v,j)=><td key={j} className={`p-2 ${i===2&&j===2?'bg-brand-50 font-semibold text-brand-900':''}`}>{v===null?'—':fmt(v)}</td>)}</tr>)}</tbody></table></div></details></section>;
}
