'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import api,{errorMessage} from '@/utils/api';
export default function SectorResearch({sector,title}:{sector:string;title:string}){
 const [profile,setProfile]=useState<any>(null),[profileError,setProfileError]=useState(''),[news,setNews]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 useEffect(()=>{let active=true;setProfile(null);setProfileError('');api.get(`/industries/sectors/${sector}/profile`).then(r=>{if(active)setProfile(r.data);}).catch(e=>{if(active)setProfileError(errorMessage(e));});return ()=>{active=false;};},[sector]);
 return <div className="mx-auto max-w-6xl space-y-6"><nav className="flex flex-wrap gap-3 text-sm">{[['real-estate','Real estate'],['technology','Technology'],['healthcare','Healthcare'],['financials','Financials']].map(([id,name])=><Link key={id} href={`/sectors/${id}`} className="rounded-lg border bg-white px-3 py-2 hover:border-brand-400">{name}</Link>)}</nav><h1 className="text-3xl font-semibold">{title} research</h1><p className="text-sm text-slate-500">Sector notes are educational. Company valuations require current filings and verified operating metrics; illustrative portfolio and debt schedules are excluded from this view.</p>
 {profileError&&<p role="alert" className="bg-amber-50 p-3 text-sm text-amber-900">{profileError}</p>}
 {profile&&<div className="grid gap-4 md:grid-cols-2">{profile.key_drivers?.map((d:any)=><article key={d.name} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{d.name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{d.description}</p>{d.why_important&&<p className="mt-2 text-sm text-slate-500">{d.why_important}</p>}</article>)}</div>}
 <Link href="/analysis/comparables" className="inline-block rounded-lg bg-brand-600 px-4 py-3 text-sm font-medium text-white">Open company comparables</Link>
 <section className="rounded-xl border bg-white p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Recent sector headlines</h2><button disabled={busy} className="rounded-lg border px-3 py-2 text-sm" onClick={async()=>{setBusy(true);setError('');setLoaded(false);setNews([]);try{setNews((await api.get('/news/latest',{params:{sector:sector.replace('_',' '),limit:10}})).data);setLoaded(true);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>{busy?'Loading…':'Load headlines'}</button></div>{error&&<p role="alert" className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{error}</p>}{loaded&&!news.length&&<p role="status" className="mt-4 text-sm text-slate-500">No matching headlines in the current feed.</p>}<div className="divide-y">{news.map(n=><article key={n.id} className="py-4"><a href={n.url} target="_blank" rel="noreferrer" className="font-medium text-brand-700 hover:underline">{n.title}</a><p className="mt-1 text-xs text-slate-500">{n.source} · {n.published_at||'Publication date unavailable'} · {n.sentiment} ({n.sentiment_method})</p><p className="mt-2 text-sm text-slate-600">{n.summary}</p></article>)}</div></section></div>;
}
