'use client';
import { useEffect, useState } from 'react';
import api,{errorMessage} from '@/utils/api';
const input='w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
const initial={revenue_growth_rates:[.1,.08,.06,.05,.05],cogs_percent_revenue:[.4,.4,.4,.4,.4],opex_fixed:0,opex_variable_pct:.15,tax_rate:.21};
export default function ThreeStatementModel(){
  const [base,setBase]=useState<any>(null),[op,setOp]=useState(initial),[years,setYears]=useState(5);
  const [wc,setWc]=useState({days_sales_outstanding:45,days_inventory_outstanding:60,days_payable_outstanding:40,accrued_liabilities_pct_revenue:.05,minimum_cash_balance:50000});
  const [fin,setFin]=useState({debt_interest_rate:.05,amortization_pct:.05,target_cash_balance:100000,dividend_payout_ratio:.2,revolver_capacity:500000,covenant_min_interest_coverage:3});
  const [cap,setCap]=useState({maintenance_capex_pct:.03,asset_life_years:10,salvage_value_pct:.05,depreciation_method:'straight_line',growth_capex:[0,0,0,0,0]});
  const [result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('Illustrative sample. Use one currency and one consistent scale throughout.');
  useEffect(()=>{api.get('/valuation/three-statement/sample-data').then(r=>setBase(r.data)).catch(e=>setError(errorMessage(e)));},[]);
  useEffect(()=>{setResult(null);},[base,op,wc,fin,cap,years]);
  const request=()=>({historical_base:base,operating_assumptions:op,wc_drivers:wc,capex_assumptions:cap,financing_assumptions:fin,projection_years:years});
  const apply=(r:any)=>{if(!r?.historical_base||!Array.isArray(r.operating_assumptions?.revenue_growth_rates))throw new Error('Invalid saved projection');setBase(r.historical_base);setOp(r.operating_assumptions);setWc(r.wc_drivers);setCap(r.capex_assumptions);setFin(r.financing_assumptions);setYears(r.projection_years);setNotice('Saved assumptions restored. Recalculate to refresh results.');};
  async function run(){setBusy(true);setError('');setResult(null);try{setResult((await api.post('/valuation/three-statement/project',request())).data);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function exportModel(){setBusy(true);try{const r=await api.post('/export/excel',{model_type:'Three_statement',ticker:'MODEL',data:result.projections},{responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download='vertige-three-statement.xlsx';a.click();URL.revokeObjectURL(url);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  const numericFields=(values:any,setValues:any,keys:string[])=>keys.map(k=><label key={k} className="block text-xs text-slate-600"><span className="mb-1 block capitalize">{k.replaceAll('_',' ')}</span><input aria-label={k.replaceAll('_',' ')} type="number" step="any" required className={input} value={values[k]??''} onChange={e=>setValues({...values,[k]:e.target.value===''?NaN:Number(e.target.value)})}/></label>);
  const metrics=['revenue','cogs','operating_expenses','ebitda','depreciation','ebit','interest_expense','tax_expense','net_income','cash','accounts_receivable','inventory','ppe_net','other_assets','total_assets','accounts_payable','accrued_liabilities','short_term_debt','long_term_debt','other_liabilities','total_liabilities','retained_earnings','total_equity','operating_cash_flow','investing_cash_flow','financing_cash_flow','net_cash_change','unlevered_fcf'];
  return <section className="space-y-6"><div className="rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-2xl font-semibold">Three-statement projection</h2><p className="mt-2 text-sm text-slate-300">Linked income statement, balance sheet and cash flows. Ratios below are decimals: 0.05 means 5%.</p></div>
    <p role="status" className="rounded-lg bg-brand-50 p-4 text-sm text-brand-900">{notice}</p>
    {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
    <div className="flex flex-wrap gap-3 text-sm">
      <button disabled={busy||!base} className="rounded-lg border px-3 py-2 disabled:opacity-50" onClick={()=>{try{localStorage.setItem('vertige-statements-v1',JSON.stringify(request()));setNotice('Projection assumptions saved in this browser.');}catch{setError('Browser storage is unavailable.');}}}>Save assumptions</button>
      <button disabled={busy} className="rounded-lg border px-3 py-2" onClick={()=>{try{const s=localStorage.getItem('vertige-statements-v1');if(!s)throw new Error('No saved projection');apply(JSON.parse(s));}catch(e){setError(errorMessage(e));}}}>Restore assumptions</button>
      <label className="rounded-lg border px-3 py-2">Import historical CSV or XLSX <input aria-label="Import historical financials" type="file" accept=".csv,.xlsx" disabled={busy} className="max-w-56 text-xs" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',file);const r=await api.post('/valuation/three-statement/upload-excel',body);setBase(r.data);setNotice(`Imported ${file.name}; confirm units and opening balances.`);}catch(err){setError(errorMessage(err));}finally{setBusy(false);e.target.value='';}}}/></label>
    </div>
    {!base&&!error&&<p role="status" className="text-sm text-slate-600">Loading sample financials…</p>}
    {base&&<form onSubmit={e=>{e.preventDefault();run();}}><fieldset disabled={busy} className="space-y-5">
      <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">Opening historical financials · editable</summary><p className="mt-2 text-xs text-slate-500">Imports use these field names as columns. The last row is the opening period. Assets must equal liabilities plus equity. Residual assets and liabilities remain constant.</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{numericFields(base,setBase,Object.keys(base).filter(k=>k!=='period'))}</div></details>
      <div className="grid gap-5 lg:grid-cols-3"><div className="rounded-xl border bg-white p-5"><h3 className="mb-4 font-semibold">Operating drivers</h3><label className="mb-4 block text-xs">Projection years<input aria-label="Projection years" className={input} type="number" min={1} max={30} value={years} onChange={e=>{const n=Math.max(1,Math.min(30,Number(e.target.value)||1));setYears(n);setOp({...op,revenue_growth_rates:Array.from({length:n},(_,i)=>op.revenue_growth_rates[i]??.05),cogs_percent_revenue:Array.from({length:n},(_,i)=>op.cogs_percent_revenue[i]??.4)});setCap({...cap,growth_capex:Array.from({length:n},(_,i)=>cap.growth_capex[i]??0)});}}/></label><div className="space-y-3">{numericFields(op,setOp,['opex_fixed','opex_variable_pct','tax_rate'])}</div></div>
      <div className="rounded-xl border bg-white p-5"><h3 className="mb-4 font-semibold">Working capital</h3><div className="space-y-3">{numericFields(wc,setWc,Object.keys(wc))}</div></div>
      <div className="rounded-xl border bg-white p-5"><h3 className="mb-4 font-semibold">Financing</h3><div className="space-y-3">{numericFields(fin,setFin,Object.keys(fin))}</div></div></div>
      <details className="rounded-xl border bg-white p-5" open><summary className="cursor-pointer font-semibold">Annual growth and investment</summary><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{numericFields(cap,setCap,['maintenance_capex_pct','asset_life_years','salvage_value_pct'])}<label className="text-xs">Depreciation<select className={input} value={cap.depreciation_method} onChange={e=>setCap({...cap,depreciation_method:e.target.value})}><option value="straight_line">Straight line</option><option value="double_declining">Double declining</option></select></label></div><div className="mt-4 max-h-64 overflow-auto"><table className="w-full text-sm"><thead><tr><th>Year</th><th>Revenue growth</th><th>COGS / revenue</th><th>Growth capex</th></tr></thead><tbody>{op.revenue_growth_rates.map((g,i)=><tr key={i}><td>{i+1}</td>{(['revenue_growth_rates','cogs_percent_revenue'] as const).map(k=><td key={k} className="p-1"><input aria-label={`${k} ${i+1}`} className={input} type="number" step="any" value={op[k][i]} onChange={e=>{const arr=[...op[k]];arr[i]=Number(e.target.value);setOp({...op,[k]:arr});}}/></td>)}<td className="p-1"><input aria-label={`growth capex ${i+1}`} className={input} type="number" value={cap.growth_capex[i]} onChange={e=>{const arr=[...cap.growth_capex];arr[i]=Number(e.target.value);setCap({...cap,growth_capex:arr});}}/></td></tr>)}</tbody></table></div></details>
      <p className="text-xs leading-5 text-slate-500">Interest uses average opening and closing debt. Short-term debt is the revolver; its capacity limits funding. New capex uses half-year depreciation. Opening net PP&E is amortized over the entered remaining life. No tax-loss carryforwards are modeled.</p>
      <button type="submit" className="rounded-xl bg-brand-600 px-6 py-3 font-semibold text-white disabled:opacity-50">{busy?'Calculating…':'Project statements'}</button>
    </fieldset></form>}
    {result&&<div className="space-y-4" data-testid="statement-results"><p className="rounded-lg bg-emerald-50 p-4 text-emerald-900">{Object.values(result.validations).every(Boolean)?'All projected statements reconcile.':'A reconciliation failed.'}</p>{result.warnings.map((w:string)=><p key={w} className="bg-amber-50 p-3 text-amber-900">{w}</p>)}<button disabled={busy} onClick={exportModel} className="rounded-lg border px-4 py-2 text-sm">Export statements to Excel</button><div className="overflow-auto rounded-xl border bg-white"><table className="w-full text-right text-xs tabular-nums"><thead><tr><th className="p-3 text-left">Metric · input currency units</th>{result.projections.map((p:any)=><th className="p-3" key={p.period}>{p.period.replace('_',' ')}</th>)}</tr></thead><tbody>{metrics.map(k=><tr key={k} className="border-t border-slate-100"><th className="whitespace-nowrap p-3 text-left font-medium capitalize">{k.replaceAll('_',' ')}</th>{result.projections.map((p:any)=><td key={p.period} className="p-3">{Number(p[k]).toLocaleString(undefined,{maximumFractionDigits:2})}</td>)}</tr>)}</tbody></table></div></div>}
  </section>;
}
