'use client';
import {useEffect, useState} from 'react';
import {Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis} from 'recharts';
import api, {errorMessage} from '@/utils/api';
import {buttonClass, fieldClass, primaryClass} from '@/utils/research';
import {downloadCSV} from '@/utils/export';

type Settings = {ticker: string; benchmark: string; period: string; riskFree: number | null};
type Benchmark = {ticker: string; observations: number; start: string; end: string; beta: number | null; correlation: number | null; annualized_active_return: number; tracking_error: number; information_ratio: number | null; methodology: string; dates: string[]; asset_returns: number[]; benchmark_returns: number[]};
type Stats = {ticker: string; period: string; source: string; fetched_at: string; methodology: string; risk_free_rate: number; observations: number; annualized_volatility: number; annualized_return: number; total_return: number; sharpe_ratio: number | null; sortino_ratio: number | null; value_at_risk_95: number; max_drawdown: number; prices: number[]; dates: string[]; daily_returns: number[]; return_dates: string[]; drawdown: number[]; rolling_volatility_21d: (number | null)[]; cumulative_performance: number[]; returns_histogram: {bins: number[]; counts: number[]}; benchmark?: Benchmark; benchmark_error?: string};
const initial: Settings = {ticker: 'AAPL', benchmark: '^GSPC', period: '1y', riskFree: 4};
const periods = ['3mo', '6mo', '1y', '2y', '5y', '10y'];
const fmt = (value: number | null, percent = false) => value === null ? '—' : (value * (percent ? 100 : 1)).toLocaleString(undefined, {maximumFractionDigits: 2}) + (percent ? '%' : '');

export default function Statistics() {
  const [settings, setSettings] = useState(initial), [request, setRequest] = useState(initial);
  const [data, setData] = useState<Stats | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [view, setView] = useState('performance');
  useEffect(() => {
    let cancelled = false; setLoading(true); setError(''); setData(null);
    api.get(`/stats/metrics/${encodeURIComponent(request.ticker)}`, {params: {period: request.period, risk_free_rate: request.riskFree! / 100, ...(request.benchmark ? {benchmark: request.benchmark} : {})}, timeout: 45000})
      .then(response => {if (!cancelled) setData(response.data);})
      .catch(e => {if (!cancelled) setError(errorMessage(e));})
      .finally(() => {if (!cancelled) setLoading(false);});
    return () => {cancelled = true;};
  }, [request]);
  function update(patch: Partial<Settings>) {setSettings({...settings, ...patch}); setData(null); setError(''); setNotice('Settings changed. Analyze to refresh results.');}
  function run() {if (!settings.ticker.trim() || settings.riskFree === null || settings.riskFree < 0 || settings.riskFree > 100) {setError('Enter a ticker and a risk-free rate from 0% to 100%.'); return;} setNotice(''); setRequest({...settings, ticker: settings.ticker.trim().toUpperCase(), benchmark: settings.benchmark.trim().toUpperCase()});}
  function save() {try {localStorage.setItem('vertige-statistics-v1', JSON.stringify(settings)); setNotice('Analysis settings saved. Price histories are always fetched again.');} catch {setError('Browser settings storage is unavailable.');}}
  function restore() {try {const value = JSON.parse(localStorage.getItem('vertige-statistics-v1') || 'null'); if (!value || typeof value.ticker !== 'string' || typeof value.benchmark !== 'string' || !periods.includes(value.period) || typeof value.riskFree !== 'number' || !Number.isFinite(value.riskFree) || value.riskFree < 0 || value.riskFree > 100) throw new Error('No valid saved statistics settings.'); setSettings(value); setData(null); setNotice('Settings restored. Analyze to fetch current data.'); setError('');} catch (e) {setError(errorMessage(e));}}
  function exportData() {
    if (!data) return;
    const rows: (string | number | null)[][] = [['Ticker', data.ticker], ['Lookback', data.period], ['Source', data.source], ['Fetched at', data.fetched_at], ['Risk-free rate (decimal)', data.risk_free_rate], ['Methodology', data.methodology], [], ['Date', 'Adjusted close', 'Daily return', 'Cumulative wealth', 'Drawdown', '21-session annualized volatility']];
    data.dates.forEach((date, i) => rows.push([date, data.prices[i], i ? data.daily_returns[i-1] : null, data.cumulative_performance[i], data.drawdown[i], i ? data.rolling_volatility_21d[i-1] : null]));
    if (data.benchmark) {const b = data.benchmark; rows.push([], ['Benchmark', b.ticker], ['Methodology', b.methodology], ['Beta', b.beta], ['Correlation', b.correlation], ['Tracking error', b.tracking_error], ['Information ratio', b.information_ratio], [], ['Matched date', 'Asset return', 'Benchmark return']); b.dates.forEach((date, i) => rows.push([date, b.asset_returns[i], b.benchmark_returns[i]]));}
    downloadCSV(`vertige-statistics-${data.ticker.replace(/[^A-Za-z0-9.-]/g, '')}.csv`, rows);
  }
  const points = data?.dates.map((date, i) => ({date, performance: (data.cumulative_performance[i]-1)*100, drawdown: data.drawdown[i]*100, volatility: i && data.rolling_volatility_21d[i-1] !== null ? data.rolling_volatility_21d[i-1]! * 100 : null})) || [];
  const histogram = data?.returns_histogram.counts.map((count, i) => ({range: `${fmt(data.returns_histogram.bins[i], true)} to ${fmt(data.returns_histogram.bins[i+1], true)}`, count})) || [];
  return <section className="mx-auto max-w-7xl space-y-7">
    <header className="border-b border-slate-300 pb-6"><h1 className="text-3xl font-semibold">Quantitative analysis</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Examine return distributions, drawdowns and changing risk across a chosen history. An optional benchmark adds a comparison on overlapping return dates.</p></header>
    <form onSubmit={e => {e.preventDefault(); run();}}><fieldset disabled={loading} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-medium">Ticker to analyze<input required className={fieldClass} value={settings.ticker} onChange={e => update({ticker: e.target.value.toUpperCase()})}/></label><label className="text-xs font-medium">Benchmark ticker (optional)<input className={fieldClass} value={settings.benchmark} onChange={e => update({benchmark: e.target.value.toUpperCase()})}/></label><label className="text-xs font-medium">Lookback period<select className={fieldClass} value={settings.period} onChange={e => update({period: e.target.value})}>{periods.map(period => <option key={period}>{period}</option>)}</select></label><label className="text-xs font-medium">Risk-free assumption (%)<input required type="number" step="any" min={0} max={100} className={fieldClass} value={settings.riskFree ?? ''} onChange={e => update({riskFree: e.target.value === '' ? null : Number(e.target.value)})}/></label></div><div className="flex flex-wrap gap-3"><button className={primaryClass}>Analyze</button><button type="button" className={buttonClass} onClick={save}>Save analysis settings</button><button type="button" className={buttonClass} onClick={restore}>Restore analysis settings</button><button type="button" disabled={!data} className={buttonClass} onClick={exportData}>Export observations</button></div></fieldset></form>
    {loading && <p role="status">Loading adjusted price histories…</p>}{error && <p role="alert" className="border border-red-200 bg-red-50 p-4 text-sm">{error}</p>}{notice && <p role="status" className="text-sm text-slate-600">{notice}</p>}
    {data && <>
      <p className="text-xs leading-5 text-slate-600">{data.ticker}: {data.dates[0]} to {data.dates.at(-1)} · {data.observations} returns · {data.source}, fetched {data.fetched_at}. Risk-free assumption {fmt(data.risk_free_rate, true)}.</p>
      <dl className="grid grid-cols-2 gap-x-5 gap-y-7 border-y border-slate-200 py-6 md:grid-cols-4">{[['Total return', data.total_return, true], ['Annual arithmetic return', data.annualized_return, true], ['Annual volatility', data.annualized_volatility, true], ['Maximum drawdown', data.max_drawdown, true], ['Sharpe ratio', data.sharpe_ratio, false], ['Sortino ratio', data.sortino_ratio, false], ['5th-percentile daily return', data.value_at_risk_95, true]].map(([label, value, percent]) => <div key={String(label)}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 text-xl font-semibold tabular-nums">{fmt(value as number | null, percent as boolean)}</dd></div>)}</dl>
      <div className="flex flex-wrap gap-2">{[['performance', 'Cumulative performance'], ['drawdown', 'Drawdown'], ['volatility', 'Rolling risk'], ['histogram', 'Return distribution']].map(([key, title]) => <button key={key} className={view === key ? primaryClass : buttonClass} aria-pressed={view === key} onClick={() => setView(key)}>{title}</button>)}</div>
      <div aria-label="Return analysis chart" className="h-80 min-w-0 w-full"><ResponsiveContainer width="100%" height="100%">{view === 'histogram' ? <BarChart data={histogram}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="range" tick={false}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" name="Daily returns" fill="#637be6"/></BarChart> : <LineChart data={points}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="date" minTickGap={70} tick={{fontSize: 11}}/><YAxis tickFormatter={value => `${value}%`} width={55}/><Tooltip formatter={(value: number) => `${value.toFixed(2)}%`}/><Line type="linear" dataKey={view} name={view === 'volatility' ? '21-session annualized volatility' : view} stroke="#637be6" dot={false} connectNulls={false}/></LineChart>}</ResponsiveContainer></div>
      {view === 'volatility' && <p className="text-xs text-slate-600">Rolling sample volatility uses 21 daily returns and annualizes by √252. Initial windows remain empty.</p>}
      {data.benchmark_error && <p role="status" className="border border-amber-200 bg-amber-50 p-4 text-sm">{data.benchmark_error}</p>}
      {data.benchmark && <section className="space-y-4 border-t border-slate-300 pt-6"><h2 className="text-xl font-semibold">Benchmark comparison · {data.benchmark.ticker}</h2><p className="text-xs text-slate-600">{data.benchmark.observations} matched returns from {data.benchmark.start} to {data.benchmark.end}.</p><dl className="grid grid-cols-2 gap-5 md:grid-cols-5">{[['Beta', data.benchmark.beta, false], ['Correlation', data.benchmark.correlation, false], ['Annual active return', data.benchmark.annualized_active_return, true], ['Tracking error', data.benchmark.tracking_error, true], ['Information ratio', data.benchmark.information_ratio, false]].map(([label, value, percent]) => <div key={String(label)}><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 font-semibold">{fmt(value as number | null, percent as boolean)}</dd></div>)}</dl><p className="text-xs leading-5 text-slate-600">{data.benchmark.methodology}</p></section>}
      <details className="border-t border-slate-200 pt-4"><summary className="cursor-pointer text-sm font-medium">Methods and observation table</summary><p className="my-4 text-sm leading-6 text-slate-600">{data.methodology} These are historical estimates. Sparse or short histories can make annualized statistics unstable; no forecast is implied.</p><div className="max-h-96 overflow-auto"><table className="w-full text-right text-xs"><thead><tr>{['Date', 'Adjusted close', 'Daily return', 'Drawdown'].map(label => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.dates.map((date, i) => <tr key={date} className="border-t border-slate-200"><th className="p-3 font-normal">{date}</th><td className="p-3">{fmt(data.prices[i])}</td><td className="p-3">{fmt(i ? data.daily_returns[i-1] : null, true)}</td><td className="p-3">{fmt(data.drawdown[i], true)}</td></tr>)}</tbody></table></div></details>
    </>}
  </section>;
}
