export type ScenarioKey = 'bear'|'base'|'bull';
export type Financials = {current_price:number;shares_outstanding_m:number;start_revenue_m:number;net_debt_m:number;tax_rate:number;da_pct:number;capex_pct:number;nwc_pct:number;minority_interest_m:number;preferred_equity_m:number;nonoperating_assets_m:number};
export type Scenario = {key:ScenarioKey;probability:number;growth_rates:number[];ebit_margins:number[];wacc:number;terminal_growth:number;rationale:string};
export type Source = {title:string;url:string;published_date:string|null;supports:string};
export type Catalyst = {title:string;due_date:string|null;status:'watch'|'upcoming'|'occurred'};
export type ResearchDraft = {company_name:string;ticker:string;currency:string;as_of:string;review_date:string|null;status:'watching'|'researching'|'reviewed'|'archived';data_origin:'illustrative'|'analyst';thesis:string;risks:string;invalidation:string;decision_notes:string;financials:Financials;scenarios:Scenario[];sources:Source[];catalysts:Catalyst[]};
export type DCFResult = {implied_price:number;upside:number;enterprise_value:number;equity_value:number;terminal_value_share_pct:number|null;warnings:string[];bridge:Record<string,number>;forecast:Array<{year:number;revenue:number;ebit:number;fcff:number;pv_fcff:number}>};
export type Evaluation = {scenarios:Record<ScenarioKey,{probability:number;result:DCFResult}>;weighted_price:number;weighted_upside:number;description:string;research_gaps:string[];calculation_version:string;sensitivity:{wacc_values:number[];growth_values:number[];prices:(number|null)[][]}};
export type ResearchCase = {id:string;revision:number;current_revision:number;created_at:string;saved_at:string;change_note:string;input_sha256:string;draft:ResearchDraft;evaluation:Evaluation};
export type CaseSummary = {id:string;revision:number;saved_at:string;company_name:string;ticker:string;currency:string;status:ResearchDraft['status'];as_of:string;review_date:string|null;data_origin:string;current_price:number;weighted_price:number;weighted_upside:number;source_count:number;gap_count:number};
export const numberFormat=(value:number)=>value.toLocaleString(undefined,{maximumFractionDigits:2});
export const fieldClass='mt-1 w-full min-w-0 rounded border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-600';
export const buttonClass='inline-flex items-center justify-center rounded border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-800 hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-600 disabled:bg-slate-100 disabled:text-slate-500';
export const primaryClass=buttonClass+' !border-brand-700 !bg-brand-700 !text-white hover:!bg-brand-800';
export function initialDraft():ResearchDraft{return {company_name:'Illustrative company',ticker:'EXAMPLE',currency:'USD',as_of:new Date().toISOString().slice(0,10),review_date:null,status:'researching',data_origin:'illustrative',thesis:'',risks:'',invalidation:'',decision_notes:'',sources:[],catalysts:[],financials:{current_price:25,shares_outstanding_m:100,start_revenue_m:1000,net_debt_m:200,tax_rate:.25,da_pct:.03,capex_pct:.04,nwc_pct:.12,minority_interest_m:0,preferred_equity_m:0,nonoperating_assets_m:0},scenarios:[{key:'bear',probability:.25,growth_rates:[.02,.02,.02,.02,.02],ebit_margins:[.16,.16,.16,.16,.16],wacc:.12,terminal_growth:.02,rationale:''},{key:'base',probability:.5,growth_rates:[.08,.06,.05,.04,.03],ebit_margins:[.2,.21,.22,.22,.22],wacc:.1,terminal_growth:.025,rationale:''},{key:'bull',probability:.25,growth_rates:[.12,.1,.08,.06,.04],ebit_margins:[.24,.25,.26,.26,.26],wacc:.09,terminal_growth:.03,rationale:''}]};}
export function downloadJSON(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
